User account creation Version 1
nyx-ei/autospm pull request #62
Opened 2024-10-07 16:33 UTC by GT-Codeur

This code is about an API that creates user account

2024-11-03 19:58 UTC, SanAlexis requested changes
Bon début.

2024-11-03 20:34 UTC, SanAlexis requested changes
## Gestion des responsabilités avec l'API
Intéressant comme début, mais il faut bien répartir les responsabilités avec l'API.

2024-11-03 20:34 UTC, SanAlexis commented on models_validators/validators.py
> +            )
Plusieurs problèmes avec cette approche:
1. L'exception `HTTPException` est une exception spécialisée qui est de la responsabilité de l'API pas la tienne.
2. Tu masques la vraie cause de l'échec de la validation en mettant tout dans le commentaire de l'exception et en forçant le code de statut à 403. La bonne approche consiste à créer des validations spécialisées et transmettre les exceptions appropriées selon la validation qui échoue. L'API va insérer le bon message dans son payload.

2024-11-03 20:34 UTC, SanAlexis commented on models_validators/validators.py
> +                                )
Même commentaire que plus haut.

2024-11-04 19:55 UTC, GT-Codeur commented on main.py
> +        )
Je ne te comprends pas bien ici. Dans mes lectures je n'ai pas vu une telle fonction.

Ici, je définis un "end point" de mon API pour créer un compte utilisateur.

2024-11-05 17:17 UTC, SanAlexis commented on courriel/email_view.py
> +    USE_CREDENTIALS=True,
Les configurations ne doivent pas être dans le code.

2024-11-05 17:18 UTC, SanAlexis commented on email_view.py
> +)
Non, il faut séparer la configuration du code.

2024-11-05 17:18 UTC, SanAlexis commented on main.py
> +    return {"message": "Hellooooo"}
Il faut toujours retirer ce type de code mort.

2024-11-06 14:31 UTC, GT-Codeur reviewed
Configurations dans le code résolu.

2024-11-08 01:08 UTC, GT-Codeur reviewed
Problèmes avec les validations tous résolus

2024-11-13 13:25 UTC, SanAlexis approved these changes

2024-11-13 13:31 UTC, merged